### ISSUE TITLE
security considerations and CORS

### ISSUE THREAD

**Issue by plehegar** [w3c/beacon#16]
[[
What are the security considerations of this document? Is there an origin-restriction on the POST URL? Should one be recommended? Does making background POST requests to other origins including sending credentials provide an increased risk of CSRF attacks? (Maybe this risk is identical to the existing risk of submitting POST forms to other origins.) Are cross-origin POST requests with credentials necessary to satisfy the purpose of the Beacon specification? If not, why add the attack surface? I understand the group has already discussed using POST vs. GET, even though this is a request that may be repeated under error conditions. But use of POST also expands the methods attackers have for conducting CSRF attacks, since many server operations will require POST.

The CORS specification is listed in the References, but doesn't seem to be referred to in the text of the specification. Are user agents intended to follow the CORS cross-origin request model when making a beacon request to a different origin? If so, is preflight required because of the non-simple Beacon-Age header?

If you haven't already, I suspect it would be worthwhile to follow up with the Web Security Interest Group or the Web Application Security Group to check with them about the potential CSRF threat and the use of CORS.
]]
https://lists.w3.org/Archives/Public/public-web-perf/2014Jul/0109.html
from @npdoty
See also http://www.w3.org/2014/10/28-webperf-irc
and http://www.w3.org/2015/10/webperf-tpac2015-minutes#item204

**Comment by igrigorik** [comment]
@npdoty ptal at https://github.com/w3c/beacon/pull/23. I believe it should address all of the above.
