### ISSUE TITLE
normativity of language in Privacy and Security section

### ISSUE THREAD

**Issue by npdoty** [w3c/beacon#25]
Although Privacy and Security is marked as non-normative, this paragraph seems to use normative language:

> Compared to the alternatives, the sendBeacon does apply two restrictions: there is no callback method, and the payload size may be restricted by the user agent. Otherwise, the sendBeacon API is not subject to any additional restrictions. The user agent should not skip or throttle processing of sendBeacon calls, as they may contain critical application state, events, and analytics data. Similarly, the user agent should not disable sendBeacon when in "incognito" or equivalent mode, both to avoid breaking the application and to avoid leaking that the user is in such mode.

If these are intended as normative, interoperability requirements, they should be marked as such. It seems like it might be more useful, rather than telling user agents that they can't disable Beacon in a private browsing mode, to simply describe the implications of disabling sendBeacon (potentially broken functionality and potential leakage of the fact that the user was browsing in such a mode).

Also, "incognito" seems specific to a single browser vendor. Maybe "a private browsing mode"?

**Comment by igrigorik** [comment]
Should be addressed via https://github.com/w3c/beacon/pull/26.
