### ISSUE TITLE
Allow setting HTTP(S) headers in beacon

### ISSUE THREAD

**Issue by bhamiltoncx** [w3c/beacon#30]
Currently, the Beacon standard doesn't allow specifying HTTP headers in the request (except for `Content-Type` when the Blob API is used).

We'd like to specify additional headers in the HTTP beacon (for example, when using zero-rating to indicate to ISPs that a request should not count against a user's data transmission quota).

This would require updating:

1. § 3.1 (sendBeacon Method) — add additional optional parameter `httpHeaders` to include object whose key-value pairs are included in the request
1. § 3.2 (Processing Model) — update `headerList` logic to start out by populating list from `httpHeaders`, if non-null

**Comment by toddreifsteck** [comment]
#27 is our current proposal for adding Headers/Method. I need to complete that PR and then browsers need to implement, but that is likely where this will be solved.

**Comment by bhamiltoncx** [comment]
Great!
2016年5月11日(水) 22:16 Todd Reifsteck <notifications@github.com>:

**Comment by igrigorik** [comment]
@bhamiltoncx Fetch (spec) integration has landed: https://github.com/whatwg/fetch/pull/388#issuecomment-253450685. Once that's implemented, you'll be able to set custom headers/methods/etc, via fetch.

Closing this bug.
