### ISSUE TITLE
Transition Level 1 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/beacon#36]
- [ ] **Known / outstanding spec issues**
  - [x] https://github.com/w3c/beacon/issues/29#issuecomment-255882261 - size enforcement.
  - [x] https://github.com/w3c/beacon/issues/37 - hide on Worker.
  - [x] Add note for keepalive flag in Fetch
- [ ] **Web platform tests**
  - [ ] https://github.com/w3c/web-platform-tests/pull/4024
- [x] **Privacy and security**
  - http://w3c.github.io/beacon/#privacy
- [x] **Implementations**
  - Chrome: [M39+](https://www.chromestatus.com/feature/5517433905348608)
  - Firefox: [M30+](https://bugzilla.mozilla.org/show_bug.cgi?id=936340)
  - Edge: [build 14342+](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/beacon/)
  - Safari: no public signals
- [x] **Public signals: adoption, feedback...**
  - https://www.chromestatus.com/metrics/feature/timeline/popularity/494

**Comment by toddreifsteck** [comment]
I completed the Web platform tests. They confirmed that only Microsoft Edge has implemented sendBeacon on Worker. We must either remove that from L1, mark as At Risk or get another UA to implement.

The tests also show some failures in Mozilla where both Edge/Chrome pass the tests and we should invite them to investigate.

**Comment by igrigorik** [comment]
> The tests also show some failures in Mozilla where both Edge/Chrome pass the tests and we should invite them to investigate.

Reviewed, my summary: https://github.com/w3c/beacon/issues/37#issuecomment-255885921

**Comment by igrigorik** [comment]
Blocked on updated tests, but otherwise we should be in shape for CR once those land.

- https://github.com/w3c/beacon/pull/39#issuecomment-283426000

**Comment by siusin** [comment]
[CR of Beacon](https://www.w3.org/TR/2017/CR-beacon-20170413/) has been published. Thanks for the work!

**Comment by igrigorik** [comment]
\o/ .. thanks everyone!
