### ISSUE TITLE
Tests for CORS and sendBeacon()

### ISSUE THREAD

**Issue by annevk** [w3c/beacon#41]
I'd like to see tests for https://github.com/w3c/beacon/commit/8a6fbdca25115aa5a66c32cfc37d4882384b3398 and bugs filed against browsers. It's important to make sure that's all implemented correctly.

If for some reason this needs to change, please escalate to Fetch.

**Comment by toddreifsteck** [comment]
See https://github.com/w3c/web-platform-tests/pull/6655 

@igrigorik

**Comment by igrigorik** [comment]
@toddreifsteck @Brandr0id thanks for the PR -- great work there!

Left a question for CORS bits: https://github.com/w3c/web-platform-tests/pull/6655#pullrequestreview-53913059

**Comment by igrigorik** [comment]
As an update, we landed https://github.com/w3c/web-platform-tests/pull/6655 -- big thanks to @Brandr0id and @toddreifsteck for contributing those tests! 

Re, CORS: as noted in https://github.com/w3c/web-platform-tests/pull/6655#pullrequestreview-56253846, we still need to wire up some CORS tests for non-safelisted payloads, hence keeping this open.

**Comment by igrigorik** [comment]
@Brandr0id any luck on your end, for the CORS bits? :)

**Comment by toddreifsteck** [comment]
Resolved by https://github.com/w3c/web-platform-tests/pull/8757
