### ISSUE TITLE
Should cross-origin beacons with an ArrayBuffer payload do a CORS preflight?

### ISSUE THREAD

**Issue by cdumez** [w3c/beacon#45]
If I understand the processing model [1] correctly:
- data is not null do corsMode will be set to "cors".
- As per [2], my understanding is that mimeType should be null, therefore, step 6 at [1] wouldn't reset corsMode.

As a result, my understanding would be that a CORS-preflight should be done. Based on my local testing, I don't think Blink does such preflight.

[1] https://w3c.github.io/beacon/#sec-processing-model
[2] https://fetch.spec.whatwg.org/#concept-bodyinit-extract

**Comment by igrigorik** [comment]
> If I understand the processing model [1] correctly:
> 
> - data is not null do corsMode will be set to "cors".
> - As per [2], my understanding is that mimeType should be null, therefore, step 6 at [1] wouldn't reset corsMode.

Yes for the first part. Unclear on the [2]: why should mimeType be null?

> As a result, my understanding would be that a CORS-preflight should be done. Based on my local testing, I don't think Blink does such preflight.

That's a known bug (see crbug.com/720283), which will be fixed with crbug.com/695939.

---

Separate from above... Fetch looks to have updated the extract definition to return a _Content-Type_ . I think we can should our algorithm as well:

> "Extract object's byte stream (transmittedData) and type (Content-Type).

**Comment by igrigorik** [comment]
@cdumez I don't believe there is anything spec actionable here. Can we resolve this one?

**Comment by cdumez** [comment]
Sure. You answered my question, thank you.
