### ISSUE TITLE
Beacon-Age registration

### ISSUE THREAD

**Issue by plehegar** [w3c/beacon#5]
We created a new HTTP header for Beacon-Age. We should consider registering it using
 http://tools.ietf.org/html/rfc3864#section-4.3

If we want a permanent status, we will need to define the ABNF, etc.; see <http://httpwg.github.io/specs/rfc7231.html#considerations.for.new.header.fields>.

This is a not blocker for CR.

**Comment by igrigorik** [comment]
@mnot any progress on this one? :)

**Comment by igrigorik** [comment]
Closed via https://github.com/w3c/beacon/commit/4349b33e50b3bf9c6ae07773c48458fd0017c940.
