### ISSUE TITLE
Typo in Privacy and Security

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/beacon#57]
Grammar typo in Privacy and Security section:
https://w3c.github.io/beacon/#privacy-and-security

Spec text:

> Compared to the alternatives, the `sendBeacon()` does apply two restrictions: there is no callback method, and the payload size can be restricted by the user agent. Otherwise, the `sendBeacon()` API is not subject to any additional restrictions.

This part reads poorly:

>  ... the `sendBeacon()` does apply ...

I'd expect the following: (like the later sentence in the section)

> ... the `sendBeacon()` API does apply ...

**Comment by igrigorik** [comment]
@JosephPecoraro ty, resolved.
