### ISSUE TITLE
The context for fetching the beacon should be "beacon"

### ISSUE THREAD

**Issue by ehsan** [w3c/beacon#7]
The fetch spec defines the context "beacon" for this feature, but the spec currently uses "ping".  I'm modifying Gecko to fetch the URL as "beacon".

cc @annevk

**Comment by igrigorik** [comment]
I don't recall why/how we arrived at "ping" in current spec.. Guessing, it was used because we didn't have "beacon" in the Fetch spec at the time. That said, aside from providing more accurate context, does this (change to "beacon") have any effect on request processing, etc?

**Comment by ehsan** [comment]
> I don't recall why/how we arrived at "ping" in current spec.. Guessing, it was used because we didn't have "beacon" in the Fetch spec at the time. That said, aside from providing more accurate context, does this (change to "beacon") have any effect on request processing, etc?

No, it shouldn't.  But note that this is now observable to script through the context attribute of the Request object attached to FetchEvents dispatched to service workers.  I don't think this was observable before service workers.

**Comment by annevk** [comment]
We changed to have both "beacon" and "ping" because people preferred for each somewhat unique context to have its own identifier.

**Comment by igrigorik** [comment]
@ehsan @annevk makes sense, thanks. Sounds like a straightforward fix...

**Comment by plehegar** [comment]
Merged. Thank you Ehsan.
