### ISSUE TITLE
Setup auto publishing

### ISSUE THREAD

**Issue by yoavweiss** [w3c/beacon#76]
The current spec is out of date and should be re-published. Might as well set up autopublishing.

/cc @caribouW3 @nicjansma

**Comment by caribouW3** [comment]
It's already in CR, we can republish CR drafts (no substantial change) or we need a CR snapshot (if substantial change since last CR). We probably need a wide/horizontal review if we need a new CR snapshot. If no substantial change were made, can we move on to PR, then REC instead?

**Comment by yoavweiss** [comment]
Looking at the [diffs](https://github.com/w3c/beacon/compare/e8f308a87a154b0538567c2f6ac4c852125199f9...HEAD#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) between the published version and the latest, it seems like the main difference is the integration with Fetch and its `keep-alive` flag. I don't think this merits a new review cycle.

**Comment by yoavweiss** [comment]
Moving to PR SGTM, as the WPTs are now green: https://wpt.fyi/results/beacon?label=experimental&label=master&aligned

IIRC, the group generally preferred the CR-snapshot Living Standard model, but in case of Beacon, there's a good chance we can get it to REC and call it done. (as we don't predict any substantive changes in its future)

**Comment by yoavweiss** [comment]
@caribouW3 - Can we move this to PR? What's the next action on that front?

**Comment by caribouW3** [comment]
@yoavweiss We need a CfC to be able to record a WG's decision (for either a new CR Snapshot or a PR)

**Comment by domenic** [comment]
A CR-snapshot living standard would work better for maintaining the spec in the face of future updates to Fetch, Web IDL, HTML, etc.

**Comment by caribouW3** [comment]
Fine by me. @yoavweiss should I issue the CfC then?

**Comment by yoavweiss** [comment]
I agree with @domenic about a CR-snapshot being the more future-proof route, especially given the work on https://github.com/wicg/unload-beacon which may be a good fit to fold into this spec (if folks are interested). I'll send a CfC for a CR snapshot.
