### ISSUE TITLE
Is "entry setings object" correct?

### ISSUE THREAD

**Issue by domenic** [w3c/beacon#78]
See https://github.com/whatwg/html/issues/1431. We've mostly managed to remove this from the web platform, and hopefully it isn't what sendBeacon() actually uses in implementations. Has anyone written web platform tests to check?

**Comment by clelland** [comment]
It doesn't look like there are WPT, but some quick testing seems to show that Chrome, Firefox and Safari all use the environment settings object from sendBeacon's global when resolving relative URLs. (and origin checking, as mentioned in the linked HTML issue, probably has to be the same.)
